sudo: required
services:
  - docker

before_install:
  - docker build -t xbumasa/fibonacci-ui-test -f ./ui/Dockerfile.dev ./ui

script:
  - docker run -e CI=true xbumasa/fibonacci-ui-test npm run test -- --coverage

after_success:
  - docker build -t xbumasa/fibonacci-ui ./ui
  - docker build -t xbumasa/fibonacci-nginx ./nginx
  - docker build -t xbumasa/fibonacci-api ./api
  - docker build -t xbumasa/fibonacci-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_ID --password-stdin
  - docker push xbumasa/fibonacci-ui
  - docker push xbumasa/fibonacci-nginx
  - docker push xbumasa/fibonacci-api
  - docker push xbumasa/fibonacci-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "fibonacci"
  env: "Fibonacci-env"
  bucket_name: "elasticbeanstalk-us-east-2-638825234179"
  bucket_path: "fibonacci"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

