version: "3"
services:
  pg:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres_password
    expose:
      - 5432

  redis:
    image: redis:latest
    expose:
      - 6379

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    depends_on:
      - pg
      - redis
    volumes:
      - /api/node_modules
      - ./api:/api
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGHOST=pg
      - PGPORT=5432
      - PGDATABASE=postgres
      - PGUSER=postgres
      - PGPASSWORD=postgres_password
    expose:
      - 5000

  ui:
    stdin_open: true
    build:
      context: ./ui
      dockerfile: Dockerfile.dev
    depends_on:
      - api
    volumes:
      - /ui/node_modules
      - ./ui:/ui
    expose:
      - 3000

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    depends_on:
      - redis
    volumes:
      - /worker/node_modules
      - ./worker:/worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    depends_on:
      - api
      - ui
    restart: always
    ports:
      - "3050:80"
